const colors = {
  light: {
    text: "#0F172A",
    tint: "#2563EB",
    background: "#EEF2FF",
    foreground: "#0F172A",
    card: "#FFFFFF",
    cardForeground: "#0F172A",
    primary: "#2563EB",
    primaryForeground: "#FFFFFF",
    secondary: "#EFF6FF",
    secondaryForeground: "#1E40AF",
    muted: "#F1F5F9",
    mutedForeground: "#64748B",
    accent: "#DBEAFE",
    accentForeground: "#1E40AF",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#E2E8F0",
    input: "#E2E8F0",
    success: "#059669",
    successFg: "#D1FAE5",
    warning: "#F97316",
    warningFg: "#FFF7ED",
    urgent: "#DC2626",
    urgentFg: "#FEE2E2",
    gradientStart: "#1D4ED8",
    gradientMid: "#2563EB",
    gradientEnd: "#3B82F6",
  },
  radius: 20,
};

export default colors;
